// Shared TypeScript interfaces for Space Prompt

import type { LucideIcon } from 'lucide-react';

/**
 * Canonical category set. The intent analyzer must resolve every request to one
 * of these, and `general` is the honest fallback when nothing else clearly fits
 * — guessing a specialised category would be worse than admitting it is broad.
 */
export type PromptCategory =
  | 'coding'
  | 'software-development'
  | 'ai-projects'
  | 'research'
  | 'study'
  | 'writing'
  | 'design'
  | 'career'
  | 'business'
  | 'marketing'
  | 'data-analysis'
  | 'automation'
  | 'general';

export type PromptVariantType = 'balanced' | 'detailed' | 'expert';

export interface GeneratedPrompt {
  title: string;
  prompt: string;
}

export interface PromptVariants {
  balanced: GeneratedPrompt;
  detailed: GeneratedPrompt;
  expert: GeneratedPrompt;
}

export type ClarificationOptionType = 'normal' | 'ai-recommend' | 'custom';

export interface ClarificationOption {
  id: string;
  label: string;
  description?: string;
  value: string;
  recommended?: boolean;
  type?: ClarificationOptionType;
}

export interface ClarificationQuestion {
  id: string;
  topic: string;
  question: string;
  description?: string;
  options: ClarificationOption[];
  allowCustom: boolean;
  required: boolean;
}

export interface ClarificationAnswer {
  questionId: string;
  selectedOptionId?: string;
  value: string;
  custom: boolean;
  delegatedToAI: boolean;
}

export interface DelegatedDecision {
  questionId: string;
  topic: string;
}

/**
 * Validated, structured prompt context assembled in Phase 9.
 */
export interface PromptContext {
  originalInput: string;
  category: PromptCategory;
  goal: string;
  summary: string;
  knownRequirements: string[];
  clarifiedRequirements: string[];
  constraints: string[];
  ambiguitiesResolved: string[];
  delegatedDecisions: DelegatedDecision[];
  expectedOutput: string | null;
  targetModel: string | null;
  templateId?: string;
  categoryHint?: string;
}

/**
 * Lifecycle of a prompt-building session.
 *
 * Phase 7 produces `draft`, `analyzing`, `analyzed` and `error`.
 * Phase 8 adds `clarifying` and `clarified`.
 * Phase 9 adds `context-ready`.
 * Later phases produce `generating` and `complete`.
 */
export type PromptSessionStatus =
  | 'draft'
  | 'analyzing'
  | 'analyzed'
  | 'clarifying'
  | 'clarified'
  | 'context-ready'
  | 'generating'
  | 'complete'
  | 'error';

/**
 * Output of the intent analyzer (Phase 7).
 *
 * This is a validated application type, never raw model output: everything here
 * has been through `parseIntentAnalysis` first. Absent from a session until the
 * analyzer has actually run, so an empty analysis is never mistaken for a real
 * one.
 */
export interface IntentAnalysis {
  /** Short label for what the user is trying to do. */
  intent: string;
  /** Canonical category, decided from the request itself — not from any hint. */
  category: PromptCategory;
  /** The outcome the user wants, in one sentence. */
  goal: string;
  /** 1-3 sentence restatement of the request. */
  summary: string;
  /** Facts the user actually stated. Never inferred, never padded. */
  knownRequirements: string[];
  /** Information genuinely needed before a good prompt can be written. */
  missingRequirements: string[];
  /** Explicit limits the user set, e.g. "Do not use Firebase". */
  constraints: string[];
  /** Genuinely unclear points worth naming. Usually short or empty. */
  ambiguities: string[];
  /** Deliverable the user asked for, or null when they did not say. */
  expectedOutput: string | null;
  /** AI model the prompt is aimed at, or null when unstated. */
  targetModel: string | null;
  /** True only when something material is missing. Mirrors missingRequirements. */
  needsClarification: boolean;
}

export interface PromptSession {
  /** Client-generated identifier for the in-memory session, not a database key. */
  id: string;
  /** Session title generated by Phase 10 engine. */
  title?: string;
  /** The user's own words, exactly as typed or dictated. */
  originalInput: string;
  status: PromptSessionStatus;
  createdAt: string;
  /**
   * Optional starting hint carried in from a dashboard chip. It is a
   * `quickCategories` slug, not a resolved `PromptCategory`, and it exists only
   * to display context — intent detection stays the analyzer's job.
   */
  categorySlug?: string;
  /** Starter template the session began from, if any. */
  templateId?: string;
  /** Category the analyzer determined. Mirrors `analysis.category`. */
  category?: PromptCategory;
  /** Validated intent analysis (Phase 7). Undefined until the analyzer runs. */
  analysis?: IntentAnalysis;
  /** Phase 8 smart clarification questions. */
  clarifications?: ClarificationQuestion[];
  /** Phase 8 answers keyed by question ID. */
  clarificationAnswers?: Record<string, ClarificationAnswer>;
  /** Deprecated backward compatibility field for selected clarifications. */
  selectedClarifications?: Record<string, string>;
  /** Phase 9 structured prompt context. */
  context?: PromptContext;
  /** Phase 10 generated prompt variants. */
  variants?: PromptVariants;
  /** Phase 12 saved prompt ID in Supabase if persisted. */
  savedPromptId?: string;
}

/* ------------------------------------------------------------------ *
 * Prompt Studio (Phase 6-11)
 * ------------------------------------------------------------------ */

/** Which surface the studio is showing. */
export type StudioStep =
  | 'compose'
  | 'analyzing'
  | 'result'
  | 'generating-clarifications'
  | 'clarifying'
  | 'review-clarifications'
  | 'context-review'
  | 'generating-prompts'
  | 'prompt-result'
  | 'error';

/** Request body accepted by `POST /api/generate`. */
export interface GenerateRequestBody {
  context: PromptContext;
}

/** Success body returned by `POST /api/generate`. */
export interface GenerateSuccessResponse {
  title: string;
  variants: PromptVariants;
}

/** Failure body returned by `POST /api/generate`. */
export interface GenerateErrorResponse {
  error: {
    code: AnalyzeErrorCode;
    message: string;
  };
}

/**
 * Failure codes shared by `/api/analyze`, `/api/clarify`, and the studio.
 *
 * Deliberately coarse: they describe what the user can do next, never what went
 * wrong inside the provider. Nothing here leaks configuration or stack traces.
 */
export type AnalyzeErrorCode =
  | 'INVALID_INPUT'
  | 'UNAUTHENTICATED'
  | 'AI_UNAVAILABLE'
  | 'AI_RATE_LIMITED'
  | 'AI_TIMEOUT'
  | 'INVALID_AI_RESPONSE'
  | 'INVALID_PROVIDER_REQUEST'
  | 'ANALYSIS_FAILED';

/** Request body accepted by `POST /api/analyze`. */
export interface AnalyzeRequestBody {
  input: string;
  /** Weak hint from a dashboard chip. Ignored when unrecognised. */
  categoryHint?: string | null;
  /** Weak hint from a starter template. Ignored when unrecognised. */
  templateId?: string | null;
}

/** Request body accepted by `POST /api/clarify`. */
export interface ClarifyRequestBody {
  input: string;
  analysis: IntentAnalysis;
  categoryHint?: string | null;
  templateId?: string | null;
}

/** Success body returned by `POST /api/clarify`. */
export interface ClarifySuccessResponse {
  clarifications: ClarificationQuestion[];
  needsClarification: boolean;
}

/** Failure body returned by `POST /api/clarify`. */
export interface ClarifyErrorResponse {
  error: {
    code: AnalyzeErrorCode;
    message: string;
  };
}

/** Success body returned by `POST /api/analyze`. */
export interface AnalyzeSuccessResponse {
  analysis: IntentAnalysis;
}

/** Failure body returned by `POST /api/analyze`. */
export interface AnalyzeErrorResponse {
  error: {
    code: AnalyzeErrorCode;
    /** Safe, user-facing sentence. Never a provider message. */
    message: string;
  };
}

/** State of the browser speech-recognition session behind the microphone. */
export type SpeechStatus = 'idle' | 'starting' | 'listening' | 'stopping' | 'unsupported';

/** Normalised speech failure. Raw vendor error strings never reach the UI. */
export type SpeechErrorCode =
  | 'not-supported'
  | 'not-allowed'
  | 'no-speech'
  | 'audio-capture'
  | 'network'
  | 'aborted'
  | 'unknown';

export interface SpeechRecognitionError {
  code: SpeechErrorCode;
  /** Human-readable sentence safe to show the user. */
  message: string;
}

/* ------------------------------------------------------------------ *
 * Authenticated workspace (Phase 5)
 * ------------------------------------------------------------------ */

/**
 * Safe, user-facing subset of the Supabase user record.
 * Deliberately excludes the Supabase user id, tokens and raw auth metadata
 * so interactive client components never receive more than they need.
 */
export interface UserDisplayData {
  /** Resolved display name: full_name -> name -> email prefix -> "User". */
  name: string;
  /** May be an empty string if the provider did not supply one. */
  email: string;
  /** One or two uppercase letters derived from the name. */
  initials: string;
  /** Validated https avatar URL, or null when unavailable. */
  avatarUrl: string | null;
}

/** Broad grouping used by the starter template library. */
export type TemplateCategory =
  | 'Coding'
  | 'Study'
  | 'Research'
  | 'Career'
  | 'Writing'
  | 'Design'
  | 'Business';

/**
 * A starter template. `starterText` is only an opening phrase — Space Prompt
 * still runs its clarification workflow on top of it. Templates never contain
 * finished prompts.
 */
export interface Template {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  icon: LucideIcon;
  starterText: string;
  tags?: string[];
  featured?: boolean;
}

export type NavIconKey = 'dashboard' | 'studio' | 'history' | 'templates' | 'favorites' | 'settings';

/** A single sidebar / drawer navigation entry. */
export interface NavItem {
  href: string;
  label: string;
  icon: NavIconKey;
  /** Renders the item as the primary workspace action. */
  emphasis?: boolean;
}


/**
  * Full schema of a saved prompt persisted in Supabase (Phase 12+).
  */
 export interface SavedPrompt {
   id: string;
   userId: string;
   title: string;
   originalInput: string;
   category: PromptCategory;
   context: PromptContext;
   balancedPrompt: string;
   detailedPrompt: string;
   expertPrompt: string;
   isFavorite: boolean;
   createdAt: string;
   updatedAt: string;
 }

 export type RefineMode =
   | 'shorter'
   | 'detailed'
   | 'technical'
   | 'beginner'
   | 'creative'
   | 'constraints'
   | 'structure'
   | 'custom';

 export interface RefineRequestBody {
   prompt: string;
   mode: RefineMode;
   instruction?: string;
   context?: PromptContext;
 }

 export interface RefineSuccessResponse {
   refinedPrompt: string;
   summaryOfChanges: string;
 }

 export interface RefineErrorResponse {
   error: {
     code: AnalyzeErrorCode;
     message: string;
   };
 }

 /* ------------------------------------------------------------------ *
  * Prompt Evaluation (Phase 15)
  * ------------------------------------------------------------------ */

 export interface PromptEvaluationDimensions {
   clarity: number;
   specificity: number;
   context: number;
   constraints: number;
   outputDefinition: number;
   actionability: number;
 }

 export interface PromptEvaluation {
   overallScore: number;
   dimensions: PromptEvaluationDimensions;
   strengths: string[];
   improvements: string[];
   summary: string;
 }

 export interface EvaluateRequestBody {
   prompt: string;
   context?: PromptContext;
   variant?: PromptVariantType;
 }

 export interface EvaluateSuccessResponse {
   evaluation: PromptEvaluation;
 }

 export interface EvaluateErrorResponse {
   error: {
     code: AnalyzeErrorCode;
     message: string;
   };
 }

